parameters:
  database_driver: pdo_mysql
  database_host: localhost
  database_port: null
  database_name: jfclaims
  database_user: root
  database_password: Ephraim76
  
  mailer_transport: gmail
  mailer_encryption: ssl
  mailer_auth_mode: login
  mailer_host: smtp.gmail.com
  mailer_username: gestione@studiolegalecarlesi.com
  mailer_password: aleantasc
  mailer_user: gestione@studiolegalecarlesi.com
  
  locale: it
  secret: 00a93fc27105f2fdf290c66c77e1e557
  database_path: null

  mail_robot: gestione@studiolegalecarlesi.com
  mail_robot_sender: Studio Legale Carlesi