parameters:
  database_driver: pdo_mysql
  database_host: 95.110.160.63
  database_port: null
  database_name: sinistri
  database_user: root
  database_password: ch3p4ll3
  
  mailer_transport: gmail
  mailer_encryption: ssl
  mailer_auth_mode: login
  mailer_host: smtp.gmail.com
  mailer_username: gestione@studiolegalecarlesi.com
  mailer_password: aleantasc
  mailer_user: gestione@studiolegalecarlesi.com
  
  locale: it
  secret: 00a93fc27105f2fdf290c66c77e1e557
  database_path: null
