ephp_email:
    resource: "@EphpEmailBundle/Controller/"
    type:     annotation
    prefix:   /

ephp_strumenti:
    resource: "@EphpStrumentiBundle/Controller/"
    type:     annotation
    prefix:   /

ephp_calendar:
    resource: "@EphpCalendarBundle/Controller/"
    type:     annotation
    prefix:   /

ephp_acl:
    resource: "@EphpACLBundle/Controller/"
    type:     annotation
    prefix:   /

ephp_sinistri:
    resource: "@EphpSinistriBundle/Controller/"
    type:     annotation
    prefix:   /
    
ephp_imap:
    resource: "@EphpImapBundle/Controller/"
    type:     annotation
    prefix:   /email

_fos:
    resource: routing_fos_user.yml