ephp_calendar:
    resource: "@EphpCalendarBundle/Controller/"
    type:     annotation
    prefix:   /

ephp_acl:
    resource: "@EphpACLBundle/Controller/"
    type:     annotation
    prefix:   /

ephp_sinistri:
    resource: "@EphpSinistriBundle/Controller/"
    type:     annotation
    prefix:   /

_fos:
    resource: routing_fos_user.yml