jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chainprovider:
            chain:
                providers: [fos_user_bundle, in_memory]
        fos_user_bundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    jfclaims:  { password: aleantasc, roles: [ 'ROLE_USER' ] }
                    eph: { password: livorno, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        public:
            pattern: /*.(csv|ics)
            security: false
        login:
            pattern:  /login$
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_user_bundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
                default_target_path: /tabellone
                remember_me: true
            logout:       true
            anonymous:    false
#        basic:
#            pattern: ^/
#            provider: in_memory
#            stateless: true
#            http_basic:
#                realm: "JFC Area"      
            
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
