<?php

namespace Ephp\Bundle\CalendarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CalendarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarioRepository extends EntityRepository
{
}
