<?php

namespace Ephp\Bundle\GestoriBundle\Entity;

use Ephp\ACLBundle\Model\BaseAccessLogRepository;

/**
 * BaseAccessLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessLogGestoreRepository extends BaseAccessLogRepository
{
}
