<?php

namespace B2S\Bundle\PortletBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LayoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LayoutRepository extends EntityRepository
{
}