<?php

namespace B2S\Bundle\PortletBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CatalogoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortletRepository extends EntityRepository {

    public function removeAllArea() {
        $connection = $this->getEntityManager()->getConnection();
        $q = "DELETE FROM portlet_catalogo_aree";
        $connection->executeUpdate($q);
    }

    public function trova($bundle, $action, $layout) {
        $out = $this->findOneBy(array(
            'bundle' => "B2S{$bundle}Bundle",
            'action' => $action,
            'layout' => $layout,
                ));
        if (!$out) {
            $out = $this->findOneBy(array(
                'bundle' => "EcoSeekr{$bundle}Bundle",
                'action' => $action,
                'layout' => $layout,
                    ));
        }
        return $out;
    }

}