services:
    my.facebook.user:
        class: Ephp\ACLBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: ~
            userManager: ~
            validator: ~
            container: ~
