<?php

namespace Ephp\Bundle\EmailBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CountdownRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountdownRepository extends EntityRepository
{
}
