<?php

namespace Ephp\Bundle\SinistriBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventoRepository extends EntityRepository {

    public function prossimiEventi(\Ephp\Bundle\CalendarBundle\Entity\Calendario $calendario, $gestore, $maxResults = 100, $firstResult = 0) {
        $today = new \DateTime();
        $today->setTime(0, 0, 0);
        $today->sub(new \DateInterval('P1D'));
        $q = $this->createQueryBuilder('e')
                ->leftJoin('e.scheda', 's')
                ->where('e.calendario = :cal')
                ->andwhere('e.data_ora > :oggi')
                ->setParameter('cal', $calendario->getId())
                ->setParameter('oggi', $today)
                ->setMaxResults($maxResults)
                ->setFirstResult($firstResult)
                ->orderBy('e.data_ora', 'ASC');
        if($gestore) {
            $q->andWhere('s.gestore = :ges')
                ->setParameter('ges', $gestore->getId());
            
        }
        return $q->getQuery()->execute();
    }

}
