<?php

namespace Ephp\Bundle\SinistriBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MedicoLegaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicoLegaleRepository extends EntityRepository
{
}
