<?php

namespace Ephp\Bundle\SinistriBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SchedaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchedaRepository extends EntityRepository {

    public function cerca($gestore, $ospedale, $anno, $find) {
        $qb = $this->createQueryBuilder('s');
        if ($gestore) {
            $qb->andWhere('s.gestore = :gestore')->setParameter('gestore', $gestore);
        }
        if (count($ospedale) > 0) {
            $qb->andWhere($qb->expr()->in('s.ospedale', $ospedale));
        }
        if ($anno) {
            $qb->andWhere('s.anno = :anno')->setParameter('anno', $anno);
        }
        $qb->andWhere('s.claimant like :q')->setParameter('q', "%{$find}%");
        return $qb->getQuery()->execute();
    }

}
